id: I695A9A72
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-05-27T15:06:29.941670'
last_modified: '2022-05-27T15:06:29.941682'
parser: null
source_metadata:
  title: 'RK: Gaṅgottaraparipṛcchā'
  language: en
  base:
    fD283:
      title: Title
      base_file: fD283.txt
      order: 1
    f4F55:
      title: Preface
      base_file: f4F55.txt
      order: 2
    fAB08:
      title: Colophon
      base_file: fAB08.txt
      order: 3
  chapter_to_tile: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
